### ISSUE TITLE
Salt supported?

### ISSUE THREAD

**Issue by stephenlautier** [griffo-io/sha3.net#35]
Is it possible somehow to pass a salt key with this? As we need to match it similar to this
https://wtools.io/generate-hmac-hash using SHA3-512 + salt key

So given the following:
Content: `Hello`
Salt key: `1234`
Hash type: `sha3-512`
Should result: `8f8a3752ee05d4465f1747918016fe2dd28fc487652efc2d32a8bce90cf8f4e53de87eccd6c0386ec18811ca8cbf37927a47b5266fb16373194be9a9b105f809`

Any help would be appreciated

**Comment by dariogriffo** [comment]
you want to use HMAC or SHA3?

**Comment by stephenlautier** [comment]
Sorry I'm not too knowledgeable with hashings/algorithms and such, so I'm a bit confused now. 

Basically I want similar to this https://www.php.net/manual/en/function.hash-hmac-algos.php with **sha3-512,** or the link i had provided (https://wtools.io/generate-hmac-hash), and in both cases it falls under **HMAC - SHA3-512** hence thats why im confused now.

Our provider is using php and generating a signature with hmac sha3-512, so we need to verify it, I tried `HMACSHA512` e.g. `new HMACSHA512(secretBytes)` but the values mismatch so I was looking into SHA3 and found this

**Comment by dariogriffo** [comment]
You probably want to look at https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.hmac.create
You can find there all the available algorithms for hmac in dot net.

**Comment by stephenlautier** [comment]
Thanks I am already looking into that. but somehow they need to exists, anyway sorry for opening the issue, but with that small comment you pointed me in the right direction.

Thanks once again.

**Comment by dariogriffo** [comment]
Good luck!
