### ISSUE TITLE
Implement HashSize and other properties

### ISSUE THREAD

**Issue by chm-tm** [griffo-io/sha3.net#36]
Set `HashAlgorithm.HashSizeValue` in the constructor.
Ensure the other properties inherited from `HashAlgorithm` do return the correct value.

**Comment by dariogriffo** [comment]
Would you like to open a PR on this?

**Comment by chm-tm** [comment]
Good idea, but I'm unable to do this now.

**Comment by dariogriffo** [comment]
1961156
